# Generated by Django 5.0.6 on 2025-01-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, upload_to='gifts/')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guests', models.ManyToManyField(blank=True, to='tenant.guest')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_gifts', to='tenant.gift')),
                ('guests', models.ManyToManyField(related_name='offered_gifts', to='tenant.guest')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='received_gifts/')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='tenant.guest')),
            ],
        ),
    ]
